
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jun 27 20:15:31 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONT = 24;
  public static final int MAP = 45;
  public static final int LBRACKET = 42;
  public static final int CHAR = 46;
  public static final int CONST = 6;
  public static final int LPAREN = 10;
  public static final int GREATER = 32;
  public static final int SEMI = 7;
  public static final int LESS = 34;
  public static final int FOR = 25;
  public static final int MINUS = 12;
  public static final int RPAREN = 11;
  public static final int AND = 36;
  public static final int OR = 37;
  public static final int BOOL = 47;
  public static final int ELESS = 35;
  public static final int COMMA = 8;
  public static final int CLASS = 14;
  public static final int INC = 38;
  public static final int PERC = 29;
  public static final int DIV = 28;
  public static final int IFDIFF = 31;
  public static final int PLUS = 26;
  public static final int IF = 16;
  public static final int DOT = 41;
  public static final int EOF = 0;
  public static final int RETURN = 21;
  public static final int RBRACKET = 43;
  public static final int EQUAL = 9;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int MUL = 27;
  public static final int NUMBER = 48;
  public static final int EGREATER = 33;
  public static final int BREAK = 13;
  public static final int IDENT = 2;
  public static final int VOID = 22;
  public static final int ARROW = 44;
  public static final int COLON = 40;
  public static final int LBRACE = 4;
  public static final int ELSE = 15;
  public static final int READ = 20;
  public static final int WHILE = 17;
  public static final int RBRACE = 5;
  public static final int EXTENDS = 23;
  public static final int PROG = 3;
  public static final int IFEQUAL = 30;
  public static final int DEC = 39;
  public static final int PRINT = 19;
}

