

//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
  /* terminals */
  public static final int PROG=0;
  public static final int BREAK=1;
  public static final int CLASS=2;
  public static final int ELSE=3;
  public static final int CONST=4;
  public static final int IF=5;
  public static final int WHILE=6;
  public static final int NEW=7;
  public static final int PRINT=8;
  public static final int READ=9;
  public static final int RETURN=10;
  public static final int VOID=11;
  public static final int EXTENDS=12;
  public static final int CONT=13;
  public static final int FOR=14;
  public static final int CHAR=15;
  public static final int BOOL=16;
  public static final int PLUS=17;
  public static final int MINUS=18;
  public static final int MUL=19;
  public static final int DIV=20;
  public static final int PERC=21;
  public static final int IFEQUAL=22;
  public static final int IFDIFF=23;
  public static final int GREATER=24;
  public static final int EGREATER=25;
  public static final int LESS=26;
  public static final int ELESS=27;
  public static final int AND=28;
  public static final int OR=29;
  public static final int INC=30;
  public static final int DEC=31;
  public static final int COLON=32;
  public static final int DOT=33;
  public static final int LBRACKET=34;
  public static final int RBRACKET=35;
  public static final int ARROW=36;
  public static final int EQUAL=37;
  public static final int SEMI=38;
  public static final int COMMA=39;
  public static final int LPAREN=40;
  public static final int RPAREN=41;
  public static final int LBRACE=42;
  public static final int RBRACE=43;
  public static final int IDENT=44;
  public static final int NUMBER=45;
  public static final int EOF=46;
}

